# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created: Mon Jan 26 17:08:22 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(723, 554)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(-1)
        self.horizontalLayout.setMargin(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setLineWidth(1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter = QtGui.QSplitter(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(300, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.saveDirectory = QtGui.QPushButton(self.groupBox)
        self.saveDirectory.setObjectName(_fromUtf8("saveDirectory"))
        self.gridLayout.addWidget(self.saveDirectory, 0, 1, 1, 1)
        self.fileOut = QtGui.QLineEdit(self.groupBox)
        self.fileOut.setEnabled(True)
        self.fileOut.setText(_fromUtf8(""))
        self.fileOut.setMaxLength(32777)
        self.fileOut.setFrame(True)
        self.fileOut.setObjectName(_fromUtf8("fileOut"))
        self.gridLayout.addWidget(self.fileOut, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tree_schedule = QtGui.QTreeView(self.groupBox)
        self.tree_schedule.setAlternatingRowColors(True)
        self.tree_schedule.setObjectName(_fromUtf8("tree_schedule"))
        self.verticalLayout_2.addWidget(self.tree_schedule)
        self.groupBox2 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox2.setFlat(True)
        self.groupBox2.setCheckable(False)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox2)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout2 = QtGui.QGridLayout()
        self.gridLayout2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout2.setVerticalSpacing(0)
        self.gridLayout2.setObjectName(_fromUtf8("gridLayout2"))
        self.loadFile = QtGui.QPushButton(self.groupBox2)
        self.loadFile.setObjectName(_fromUtf8("loadFile"))
        self.gridLayout2.addWidget(self.loadFile, 0, 1, 1, 1)
        self.fileIn = QtGui.QLineEdit(self.groupBox2)
        self.fileIn.setEnabled(True)
        self.fileIn.setObjectName(_fromUtf8("fileIn"))
        self.gridLayout2.addWidget(self.fileIn, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout2)
        self.tree_file = QtGui.QTreeView(self.groupBox2)
        self.tree_file.setAlternatingRowColors(True)
        self.tree_file.setIndentation(20)
        self.tree_file.setObjectName(_fromUtf8("tree_file"))
        self.verticalLayout_3.addWidget(self.tree_file)
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.plot1 = PlotWidget(self.splitter_2)
        self.plot1.setAcceptDrops(False)
        self.plot1.setObjectName(_fromUtf8("plot1"))
        self.plot2 = PlotWidget(self.splitter_2)
        self.plot2.setObjectName(_fromUtf8("plot2"))
        self.horizontalLayout.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fileOut, self.saveDirectory)
        MainWindow.setTabOrder(self.saveDirectory, self.tree_schedule)
        MainWindow.setTabOrder(self.tree_schedule, self.fileIn)
        MainWindow.setTabOrder(self.fileIn, self.loadFile)
        MainWindow.setTabOrder(self.loadFile, self.tree_file)
        MainWindow.setTabOrder(self.tree_file, self.plot2)
        MainWindow.setTabOrder(self.plot2, self.plot1)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Schedule", None))
        self.saveDirectory.setText(_translate("MainWindow", "Output Directory", None))
        self.groupBox2.setTitle(_translate("MainWindow", "File", None))
        self.loadFile.setText(_translate("MainWindow", "Design File", None))

from pyqtgraph import PlotWidget
